### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Reneeeeeeeeeeee**
index update for week2 
http://18.221.31.109:3000/

### CODE REVIEW

**Review by cwpeng — COMMENTED** [review]
Your website cannot work properly for now.

**Comment by Reneeeeeeeeeeee** [comment]
Hi Peng, the problem has been solved.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Your code will load the same page multiple times if we scroll down and up quickly.
2. Aspect ratio of any images in your page should keep the same as original ones.
未命名-2

**Comment by Reneeeeeeeeeeee** [comment]
Hi PengPeng,

I have solved the first issue. However, I'm not clear about the second
issue. Do you mean when I adjust different screen sizes, the image ratio
should remain the same?

Kind regards,
Renee

**Comment by cwpeng** [comment]
Yes. image ratio should remain the same in any situation.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Aspect ratio of any images in your page should keep the same as original ones.

**Review by cwpeng — COMMENTED** [review]
Website is broken for now.

**Comment by Reneeeeeeeeeeee** [comment]
Hi, Peng peng 
Sorry for the inconvenience, I've solved the issue.

**Review by cwpeng — APPROVED** [review]
OK. Done. Keep Going.

**Pull request merged**
