### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Reneeeeeeeeeeee**
http://18.221.31.109:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
We have to delete booking data after successful ordering.

**Comment by Reneeeeeeeeeeee** [comment]
Hi PengPeng,

Do you mean the one I saved as the token ?

Renee

**Comment by cwpeng** [comment]
If we order successfully and back to booking page, it should be empty.

**Comment by Reneeeeeeeeeeee** [comment]
Hi PengPeng, the issue has been solved.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
