### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Reneeeeeeeeeeee**
http://18.221.31.109:3000/
http://18.221.31.109:3000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your APIs are broken.

**Comment by Reneeeeeeeeeeee** [comment]
Hi, PengPeng It has been solved.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Border style of radio input and button.
2. Layout exceeds screen width in small to middle size deivces.

**Comment by Reneeeeeeeeeeee** [comment]
Hi Peng I think the issues have been solved. Thanks.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Layout is still borken in mobile version, there exists horizontal scrollbar in your page.
18 221 31 109_3000_attraction_10(iPhone XR)

**Comment by Reneeeeeeeeeeee** [comment]
Hi, PengPeng the issue has been solved!

**Review by cwpeng — CHANGES_REQUESTED** [review]
The same issue in middle size devices.
18 221 31 109_3000_attraction_10

**Comment by Reneeeeeeeeeeee** [comment]
Hi, PengPeng I've changed the layout but not sure this meets the requirement.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Layout should never exceed screen width in any size of devices. There should not exists horizontal scroll bar in any size of devices.
2. Aspect ratio of any images in your page should keep the same as original ones. Your photo slider in attraction page changes aspect ratio of images in mobile version.
3. In fact, there are many small styling and layout issues in your page. Try to take more attention on aligning with design.
18 221 31 109_3000_attraction_10
未命名-2

**Comment by Reneeeeeeeeeeee** [comment]
Hi PengPeng, I think I have fixed the issues you mentioned above. I've noticed that I checked the layout by clicking the specific size and thus may ignore the screen sizes in between. Thanks ever so.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
