### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Reneeeeeeeeeeee**
Hi Peng Peng, I'm Renee, I apologize for the delay in completing the assignment. Following urls are for the week1 assignment. 
 http://18.221.31.109:3000/api/attractions?page=1
[http://18.221.31.109:3000/api/attractions?page=0&keyword=藝文館所](http://18.221.31.109:3000/api/attractions?page=0&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80)
[http://18.221.31.109:3000/api/attractions?page=0&keyword=北](http://18.221.31.109:3000/api/attractions?page=0&keyword=%E5%8C%97)
http://18.221.31.109:3000/api/attraction/10
Thanks in advance.

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Response of http://18.221.31.109:3000/api/categories should be a 1 dimension array containing category names.
2. "images" field of attraction should be a string array containing every image URLs. For example: ["Image URL 1", "Image URL 2", ...]. But yours is actually a string "['Image URL 1', 'Image URL 2', ...]"

Solve issues and re-request review.

**Comment by Reneeeeeeeeeeee** [comment]
Hi Peng Peng , thanks for your feedback, I've solved the problems!

**Review by cwpeng — COMMENTED** [review]
But your live URLs are break.

**Comment by Reneeeeeeeeeeee** [comment]
Hi Peng I've fixed the problem. Please try again :)

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your `images` field in every attraction are all the same, fix this issue and re-request review.

**Comment by Reneeeeeeeeeeee** [comment]
Hi Peng Peng thanks for noticing the issue, it has been solved.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
